server:
  port: 8087

spring:
  application:
    name: Transaction-service
  cloud:
    nacos:
      server-addr: 47.129.197.205:29522 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: 1234
  rabbitmq:
    host: 47.129.197.205
    port: 30272
    virtual-host: md
    username: md
    password: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 积分记录接口文档
    description: "积分记录接口文档"
    concat: ISS-7
    version: v1.0.0
    group:
      default:
        group-name: ISS-7
        api-rule: package
        api-rule-resources:
          - com.example.demo.transaction.Controller


