server:
  port: 8088

spring:
  main:
    allow-circular-references: true
  application:
    name: Product-service
  redis:
    host: 122.51.221.6
    port: 30079
    password: JqA5i2JrtjpHTYDHiEDT
    database: 10
  cloud:
    nacos:
      server-addr: 122.51.221.6:29887 # nacos地址
    sentinel:
      transport:
        dashboard: 122.51.221.6:8090
      eager: true
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: 123456
  rabbitmq:
    host: 122.51.221.6
    port: 30272
    virtual-host: md
    username: md
    password: 123

logging:
  level:
    org:
      elasticsearch=DEBUG:

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 商品服务接口文档
    description: "商品服务接口文档"
    concat: ISS-7
    version: v1.0.0
    group:
      default:
        group-name: ISS-7
        api-rule: package
        api-rule-resources:
          - com.example.demo.product.Controller


