server:
  port: 8088

spring:
  application:
    name: Product-service
  redis:
    host: 47.129.197.205
    port: 30007
    password: JqA5i2JrtjpHTYDHiEDT
    database: 0
  cloud:
    nacos:
      server-addr: 13.251.129.185:31352 # nacos地址
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: 1234
  rabbitmq:
    host: 13.251.129.185
    port: 31681
    virtual-host: md
    username: md
    password: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 商品服务接口文档
    description: "商品服务接口文档"
    concat: ISS-7
    version: v1.0.0
    group:
      default:
        group-name: ISS-7
        api-rule: package
        api-rule-resources:
          - com.example.demo.product.Controller


