server:
  port: 8086

spring:
  main:
    allow-circular-references: true
  application:
    name: PayOrder-service
  cloud:
    nacos:
      server-addr: 122.51.221.6:29887 # nacos地址
    sentinel:
      transport:
        dashboard: 122.51.221.6:8090
      eager: true
  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: 1234
  rabbitmq:
    host: 122.51.221.6
    port: 30272
    virtual-host: md
    username: md
    password: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 支付服务接口文档
    description: "支付服务接口文档"
    concat: ISS-7
    version: v1.0.0
    group:
      default:
        group-name: ISS-7
        api-rule: package
        api-rule-resources:
          - com.example.demo.payOrder.Controller



